#!/usr/bin/env python

from matplotlib import pyplot as plt
import upcycle as U
import upcycle.chartutils as CU
import numpy as np
import os

arch =  U.arch.arch_factory('hier', dict(
    vbits=512,
    geom=U.arch.ntiles_to_geom(2048),
    compute_scale=[0.5, 1, 2, 10, 100, 0],
    noc_scale=[0.5, 1, 2, 10, 100, 0]))

arch_ext = U.simdb.ArchExtConfig(2.4e9, 900 * 2**30, 1.0, 1.0, 1.0)
db = U.simdb.SimDb(arch)

fig = plt.figure(figsize=(12, 3.5))
(ismall, ilarge, tsmall, tlarge) = fig.subplots(
    1, 4,
    sharey=True)
    # gridspec_kw={'width_ratios': [len(apps.nv_infer_apps), len(apps.nv_train_apps)]})
BAR_W = 0.44
HEIGHT = 10

print(f'area: {db.area_mm2():.2f} mm2')


def make_plot(ax, apps : dict[str, U.apps.Trace], labels : list[str], mode : str = 'infer', batch : str = 'offline', ylabel=True, legend=True):
    speedup = [
        db.perf(apps[appname], arch_ext) / U.nvdb.get_perf(appname.split('-')[0], mode, batch)
        for appname in apps.keys()
    ]

    poweff = [
        U.nvdb.pj_per_op(appname.split('-')[0], mode, batch) / db.pj_per_op(apps[appname], arch_ext)
        for appname in apps.keys()
    ]

    speedup += [U.stats.geo_mean(speedup)]
    poweff += [U.stats.geo_mean(poweff)]

    print(f'Speedup {mode} {batch}: {speedup}')
    print(f'Power {mode} {batch}: {poweff}')
    print()

    pos = np.arange(len(speedup))
    r1 = ax.bar(pos - BAR_W / 2, speedup, BAR_W, label='Speedup', color='#4E67C8')
    r2 = ax.bar(pos + BAR_W / 2, poweff, BAR_W, label='Rel. Efficiency', color='#5DCEAF')

    for i in range(len(speedup)):
        if speedup[i] > HEIGHT:
            ax.annotate(
                f'{int(speedup[i])}',
                (pos[i] - BAR_W / 2, HEIGHT - 0.75),
                textcoords="offset points",
                xytext=(0, 0),
                ha='center',
                fontsize=10 if speedup[i] < 100 else 7,
                color='#000000')

        if poweff[i] > HEIGHT:
            ax.annotate(
                f'{int(poweff[i])}',
                (pos[i] + BAR_W / 2, HEIGHT - 0.75),
                textcoords="offset points",
                xytext=(0, 0),
                ha='center',
                fontsize=10 if poweff[i] < 100 else 7,
                color='#FFFFFF')

    ax.set_xticks(pos)
    ax.set_xticklabels(labels + ['geomean'], rotation=90)
    if ylabel:
        ax.set_ylabel('Speedup over A100')

    if legend:
        ax.legend(loc='upper center')


# make_plot(ismall, infer_online, appnames, 'infer', 'online', ylabel=True, legend=False)
make_plot(ilarge, CU.infer_offline, CU.appnames, 'infer', 'offline', ylabel=False, legend=False)
# make_plot(tsmall, train_small, appnames, 'train', 'small', ylabel=False, legend=False)
make_plot(tlarge, CU.train_large, CU.appnames, 'train', 'large', ylabel=False, legend=False)

# ismall.set_xlabel('(a) Small Batch\nInference')
ilarge.set_xlabel('(a) Inference')
# tsmall.set_xlabel('(c) Small Batch\nTraining')
tlarge.set_xlabel('(b) Training')

ilarge.legend(loc='upper right', borderaxespad=-0.1, framealpha=1.0)
plt.ylim([0, HEIGHT])
plt.tight_layout()
os.makedirs('./figs', exist_ok=True)
plt.savefig('figs/perf_compare.pdf')
