#!/usr/bin/env python

from matplotlib import pyplot as plt
import upcycle as U
import upcycle.chartutils as CU
import numpy as np
import os

colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']

arch_cfgs = [
    (256, 1024),
    (256, 2048),
    (256, 4096),
    (512, 1024),
    (512, 2048),
    (512, 4096),
]

freqs = list(range(int(1.0e9), int(3.0e9), int(100e6)))
fig = plt.figure(figsize=(14, 5))
axs = fig.subplots(2, len(CU.appnames))
plt.subplots_adjust(wspace=0.5)

for c, appname in enumerate(CU.appnames):
    for r, mode in enumerate(['infer', 'train']):
        batch = 'offline' if mode == 'infer' else 'large'
        app = CU.apps[f'{appname}-{mode}-{batch}']

        base_pow = None
        base_area = None

        best_cfg = None
        best_pow = None
        best_area = None

        for i, (vbits, ncores) in enumerate(arch_cfgs):
            pj_per_op = []
            tops_per_mm2 = []

            arch =  U.arch.arch_factory('hier', dict(
                vbits=vbits,
                geom=U.arch.ntiles_to_geom(ncores),
                compute_scale=[0.5, 1, 2, 10, 100, 0],
                noc_scale=[0.5, 1, 2, 10, 100, 0]))

            arch_notp =  U.arch.arch_factory('hier', dict(
                vbits=vbits,
                geom=U.arch.ntiles_to_geom(ncores),
                compute_scale=[0.5, 1, 2, 10, 100, 0],
                noc_scale=[0.5, 1, 2, 10, 100, 0]))

            db = U.simdb.cached_simdb(arch, node=12, num_hbms=2)
            db_notp = U.simdb.cached_simdb(arch_notp, node=12, num_hbms=2)

            for freq in freqs:
                arch_ext = U.simdb.ArchExtConfig(freq, CU.base_membw)
                if db.perf(app, arch_ext) > db_notp.perf(app, arch_ext):
                    pj_per_op = db.pj_per_op(app, arch_ext)
                    tops_per_mm2 = db.tops_per_mm2(app, arch_ext)
                else:
                    pj_per_op = db_notp.pj_per_op(app, arch_ext)
                    tops_per_mm2 = db_notp.tops_per_mm2(app, arch_ext)

                if vbits == 512 and ncores == 2048 and freq == 2.4e9:
                    base_pow = pj_per_op
                    base_area = tops_per_mm2

                # peak_ops = ncores * vbits / 8 * 2 * freq

                # if np.abs(peak_ops - 624e12) / 624e12 > 0.05: continue
                if best_pow is None or pj_per_op < best_pow:
                    best_pow = pj_per_op
                    best_area = tops_per_mm2
                    best_cfg = (vbits, ncores, freq)

        (vbits, ncores, freq) = best_cfg
        peak_ops = ncores * vbits / 8 * 2 * freq

        print('\t'.join([
            f'{appname}-{mode}-{batch}:\t {vbits}-bit',
            f'{ncores}-{freq/1e9:.2f}-{peak_ops/1e12:.2f}',
            f'{best_pow:.2f} pJ/op',
            f'{best_area:.2f} TOPS/mm2',
            f'area_ratio = {best_area / base_area:.2f}',
            f'power_ratio = {best_pow / base_pow:.2f}',
        ]))