#!/usr/bin/env python
from dataclasses import dataclass, replace
import functools
import numpy as np
import upcycle as U

def conv_from_amos_data(n, c, k, p, q, r, s, stride):
    h = (p - 1) * stride + r
    w = (q - 1) * stride + s

    return U.ops.Conv(dtype=U.Dtype.FP16, fwd=True, n=n, si=(h, w), c=c, so=(p, q), k=k, sf=(r, s), stride=stride, pad=0)

data = """
16 3 64 112 112 7 7 2
16 64 64 56 56 3 3 1
16 64 64 56 56 1 1 1
16 64 128 28 28 3 3 2
16 64 128 28 28 1 1 2
16 128 128 28 28 3 3 1
16 128 256 14 14 3 3 2
16 128 256 14 14 1 1 2
16 256 256 14 14 3 3 1
16 256 512 7 7 3 3 2
16 256 512 7 7 1 1 2
16 512 512 7 7 3 3 1
"""

def parse_data(data):
    for line in data.strip().splitlines():
        line = line.strip()
        if not line: continue
        yield conv_from_amos_data(*map(int, line.split()))

convs = list(parse_data(data))


for i, c in enumerate(convs):
    print(f'[{i}] {c}    \t {c.flops / (c.total_read_bytes + c.total_weight_bytes):.2f}')
