#!/bin/bash

# set -x
APPS=${APPS:-resnet50 ssdrn34-300 unet bert-large-pretrain rnnt dlrm}
PORTS=${PORTS:-1}
ARCHS=${ARCHS:-hier}
PAR=${PAR:-40}

for APP in $APPS; do
    for PORT in $PORTS; do
        for ARCH in $ARCHS; do
            python -OO scripts/app -t -a $APP -b small -p$PAR --noc-ports=$PORT -r $ARCH
            echo ""
            python -OO scripts/app -t -a $APP -b large -p$PAR --noc-ports=$PORT -r $ARCH
            echo ""
        done
    done
done
