#!/bin/bash

# set -x
APPS=${APPS:-resnet50 ssdrn34-1200 unet bert-large-squad rnnt dlrm}
PORTS=${PORTS:-1}
ARCHS=${ARCHS:-hier}
PAR=${PAR:-40}

for APP in $APPS; do
    for PORT in $PORTS; do
        for ARCH in $ARCHS; do
            python -OO scripts/app -i -a $APP -b online -p$PAR --noc-ports=$PORT -r $ARCH
            echo ""
            python -OO scripts/app -i -a $APP -b offline -p$PAR --noc-ports=$PORT -r $ARCH
            echo ""
        done
    done
done
