#!/bin/bash

set -x
set -e

python -OO scripts/app -i -a resnet50 -b online -p40
python -OO scripts/app -i -a resnet50 -b offline -p40

python -OO scripts/app -i -a ssdrn34-1200 -b online -p20
python -OO scripts/app -i -a ssdrn34-1200 -b offline -p20

python -OO scripts/app -i -a unet -b online -p6
python -OO scripts/app -i -a unet -b offline -p6

python -OO scripts/app -i -a bert-large-squad -b online -p20
python -OO scripts/app -i -a bert-large-squad -b offline -p20

python -OO scripts/app -i -a rnnt -b online -p20
python -OO scripts/app -i -a rnnt -b offline -p20
